# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Leukos/delivery/CCP/R-Type/r-type-mirror

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Leukos/delivery/CCP/R-Type/r-type-mirror

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Leukos/delivery/CCP/R-Type/r-type-mirror/CMakeFiles /home/Leukos/delivery/CCP/R-Type/r-type-mirror//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Leukos/delivery/CCP/R-Type/r-type-mirror/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named myclean

# Build rule for target.
myclean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 myclean
.PHONY : myclean

# fast build rule for target.
myclean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myclean.dir/build.make CMakeFiles/myclean.dir/build
.PHONY : myclean/fast

#=============================================================================
# Target rules for targets named myfclean

# Build rule for target.
myfclean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 myfclean
.PHONY : myfclean

# fast build rule for target.
myfclean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myfclean.dir/build.make CMakeFiles/myfclean.dir/build
.PHONY : myfclean/fast

#=============================================================================
# Target rules for targets named myre

# Build rule for target.
myre: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 myre
.PHONY : myre

# fast build rule for target.
myre/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myre.dir/build.make CMakeFiles/myre.dir/build
.PHONY : myre/fast

#=============================================================================
# Target rules for targets named rtype_server

# Build rule for target.
rtype_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rtype_server
.PHONY : rtype_server

# fast build rule for target.
rtype_server/fast:
	$(MAKE) $(MAKESILENT) -f src/server/CMakeFiles/rtype_server.dir/build.make src/server/CMakeFiles/rtype_server.dir/build
.PHONY : rtype_server/fast

#=============================================================================
# Target rules for targets named server_clean

# Build rule for target.
server_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server_clean
.PHONY : server_clean

# fast build rule for target.
server_clean/fast:
	$(MAKE) $(MAKESILENT) -f src/server/CMakeFiles/server_clean.dir/build.make src/server/CMakeFiles/server_clean.dir/build
.PHONY : server_clean/fast

#=============================================================================
# Target rules for targets named server_fclean

# Build rule for target.
server_fclean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server_fclean
.PHONY : server_fclean

# fast build rule for target.
server_fclean/fast:
	$(MAKE) $(MAKESILENT) -f src/server/CMakeFiles/server_fclean.dir/build.make src/server/CMakeFiles/server_fclean.dir/build
.PHONY : server_fclean/fast

#=============================================================================
# Target rules for targets named rtype_client

# Build rule for target.
rtype_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rtype_client
.PHONY : rtype_client

# fast build rule for target.
rtype_client/fast:
	$(MAKE) $(MAKESILENT) -f src/client/CMakeFiles/rtype_client.dir/build.make src/client/CMakeFiles/rtype_client.dir/build
.PHONY : rtype_client/fast

#=============================================================================
# Target rules for targets named client_clean

# Build rule for target.
client_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client_clean
.PHONY : client_clean

# fast build rule for target.
client_clean/fast:
	$(MAKE) $(MAKESILENT) -f src/client/CMakeFiles/client_clean.dir/build.make src/client/CMakeFiles/client_clean.dir/build
.PHONY : client_clean/fast

#=============================================================================
# Target rules for targets named client_fclean

# Build rule for target.
client_fclean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client_fclean
.PHONY : client_fclean

# fast build rule for target.
client_fclean/fast:
	$(MAKE) $(MAKESILENT) -f src/client/CMakeFiles/client_fclean.dir/build.make src/client/CMakeFiles/client_fclean.dir/build
.PHONY : client_fclean/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... client_clean"
	@echo "... client_fclean"
	@echo "... myclean"
	@echo "... myfclean"
	@echo "... myre"
	@echo "... server_clean"
	@echo "... server_fclean"
	@echo "... rtype_client"
	@echo "... rtype_server"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

