set(CMAKE_PREFIX_PATH "${SFML_INSTALL_DIR};${CMAKE_PREFIX_PATH}")
find_package(SFML 2.5 REQUIRED COMPONENTS system window graphics network)

set(SFML_FOUND ${SFML_FOUND} PARENT_SCOPE)
set(SFML_INCLUDE_DIR ${SFML_INCLUDE_DIR} PARENT_SCOPE)
set(SFML_LIBRARIES ${SFML_LIBRARIES} PARENT_SCOPE)